services:
  frontend:
    build:
      context: ./oshigoto
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VUE_APP_SERVER_URL=http://localhost:8000/
  backend:
    build:
      context: ./oshigotoapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"